#!/bin/bash

PATH="$PATH:$(dirname "$0")"

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <pid>"
  exit 1
fi

pid="$1"
ns="ns-$pid"
inner_ip="$(pid2ip "$pid")"
outer_ip="$(pid2ip "$pid" -o)"

ip netns add $ns
if [ $? -ne 0 ]; then
  echo "cannot create namespace for PID $pid"
  exit 1
fi

ip -n "$ns" link set dev lo up

ip -n "$ns" add
