#!/bin/bash

PATH="$PATH:$(dirname "$0")"

if [ "$#" -ne 1 ]; then
  echo "usage: $0 <pid>"
  exit 1
fi

pid="$1"
ns="ns-$pid"
ipv6="$(pid2ip "$pid")"
ipv4="$(pid2ip "$pid" -4)"

# create network namespace
ip netns add $ns
if [ $? -ne 0 ]; then
  echo "cannot create namespace for PID $pid"
  exit 1
fi

# enable loopback
ip -n "$ns" link set dev lo up

# add a virtual ethernet between namespaces
veth_in="veth-in-$pid"
veth_out="veth-out-$pid"
ip link add "$veth_in" type veth peer name "$veth_out"
ip link set "$veth_in" netns "$ns"

ip link set dev "$veth_out" up
ip -n "$ns" link set dev "$veth_in" up

# bind to bridge
ip link set dev "$veth_out" master ns-bridge

# setup ip addressing
ip -n "$ns" addr add "$ipv6/96" dev "$veth_in" 
ip -n "$ns" addr add "$ipv4/8" dev "$veth_in" 

# and routing
ip -n "$ns" route add default via ::FFFF:1
ip -n "$ns" route add default via 240.0.0.1

echo "$ns"
