#!/bin/bash

pid="false"
v4="false"

for arg in "$@"; do
  if [ "$arg" = "-4" ]; then
    v4="true"
  elif [ "$arg" = "-6" ]; then
    v4="false"
  else
    pid="$arg"
  fi
done

if [ "$pid" = "" ]; then
  echo "usage: $0 <pid> [-o]"
  echo "  -o  outer address"
  exit 1
fi

pid_hex=$(printf "%06x" $pid)
ip=""

if [ "$v4" = "true" ]; then
  # 240.0.0.0/4 for experimental use
  ip="240.$((0x${pid_hex:0:2})).$((0x${pid_hex:2:2})).$((0x${pid_hex:4:2}))"
else
  # I THINK this falls under the depracated IPv4-Compatible block...
  ip="::${pid_hex:0:2}:${pid_hex:2:4}"
fi

echo "$ip"
exit 0
